import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css';
import { SocketClient } from '../@codehooks/socket';

const Home: NextPage = () => {
  const [apiMessage, setApiMessage] = useState('');
  const [dateTime, setDateTime] = useState('');

  // REST COMMUNICATION EXAMPLE
  useEffect(() => {
    fetch(`${process.env.NEXT_PUBLIC_API_PATH}/hello`)
      .then((res) => res.json())
      .then((data) => {
        setApiMessage(data.message);
      });
  }, []);

  // SOCKET COMMUNICATION EXAMPLE
  useEffect(() => {
    const socket = new SocketClient(process.env.NEXT_PUBLIC_API_PATH);

    const connect = async () => {
      await socket.connect();

      socket.on('connect', () => {
        console.log('connected');
      });

      socket.on('datetime', (dateTime: string) => {
        console.log('datetime', dateTime);
        setDateTime(dateTime);
      });

      socket.emit('hello', 'Hello from client...');
      socket.emit('hallaisen', 'Hallaisen from client...');
    };

    connect();

    return () => {
      socket.disconnect();
    };
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        {apiMessage && (
          <h2 className={styles.subtitle}>
            with <a href="https://codehooks.io">{apiMessage}!</a>
          </h2>
        )}

        {dateTime && <code className={styles.code}>{dateTime}</code>}

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
